### ISSUE TITLE
Documentation is out of date

### ISSUE THREAD

**Issue by ayalash** [getweber/cob#115]
Cob documentation on readthedocs server was last built on Dec. 6, 2018. 12:52 p.m (https://readthedocs.org/projects/cob/builds/8209053/).
Cob's last commit was a PR which was merged 2 weeks ago.

**Comment by ayalash** [comment]
@vmalloc Please assist

**Comment by vmalloc** [comment]
It's supposed to work now. Fixed and moved to use webhooks for documentation building
