### ISSUE TITLE
Unittests - what is the best way to unittest individual models? 

### ISSUE THREAD

**Issue by d1618033** [getweber/cob#135]
I wanted to write a few unittests for my models, but had a few difficulties and was hoping I could get advice on the proper way to do this in cob.

Essentially, the issue is that I would like to place my unittests inside a tests folder, but because the cob project isn't a python package it makes it a bit difficult to import modules (I get `ValueError: attempted relative import beyond top-level package` when trying `from ... import models`)

Other hacks don't work either - e.g, if `sys.path.append('..'); import models` is put outside the test function (or fixture) I get the error `AttributeError: 'NoneType' object has no attribute 'Model'`, and even when I put it inside the test function I get the error `sqlalchemy.exc.InvalidRequestError: Table 'person' is already defined for this MetaData instance`

A solution I found, which might be a bit hackish, but it works, is the following:

```python
# file: models.py

# cob: type=models
from cob import db


class Person(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    first_name = db.Column(db.String)
    last_name = db.Column(db.String)

    @property
    def full_name(self):
        return f"{self.first_name} {self.last_name}"
```

```python
# file: tests/conftest.py

import pytest
from cob.project import get_project


@pytest.fixture
def models(webapp):
    project = get_project()
    models = project.subsystems.models.grains[0].load()  # assume only one models grain
    return models


@pytest.fixture
def _db(models):
    return models.db
 ```

```python
# file: tests/test_models.py

def test_person(models, db_session):
    p = models.Person(first_name="First", last_name="Last")
    db_session.add(p)
    db_session.commit()
    assert p.full_name == "First Last"
    people = models.Person.query.all()
    assert len(people) == 1
    assert people[0].full_name == "First Last"
```

```
# file: .cob-project.yml
name: people
deps:
  - pytest-flask-sqlalchemy
```

```
# file: setup.cfg
[tool:pytest]
mocked-sessions=cob.ctx.context.db.session
```

I added [pytest-flask-sqlalchemy](https://pypi.org/project/pytest-flask-sqlalchemy/) to the dependencies in `.cob-project.yml` to make sure the changes to the database are cleared after the tests are done.

This works, but I'm wondering if there is a better way maybe?

**Comment by vmalloc** [comment]
A very simple solution is to do this:
```python
def test_something(webapp):
    from _cob import models
    ....
```

We can consider adding a more "minimalistic" fixture in case you only need you the project path and not the full webapp fixture, but this should do the trick

**Comment by d1618033** [comment]
Very cool! Would it be OK if I added a note to the [Testing](https://cob.readthedocs.io/en/stable/testing.html) section in the documentation on how to import modules for unit testing?

**Comment by vmalloc** [comment]
Sure, that sounds great!
