### ISSUE TITLE
cob app inside celery worker does not have a testing mode

### ISSUE THREAD

**Issue by sivanbecker** [getweber/cob#143]
during development, flask app config contains 'TESTING' =True.
when starting celery with `cob celery start-worker` we dont have a way to make celery run cob in test mode.

So if develop/testing app configuration is needed, the local server will use it while async tasks will not be aware of it.

**Comment by sivanbecker** [comment]
@vmalloc is my observation correct?

**Comment by vmalloc** [comment]
Yeah, sounds reasonable
