### ISSUE TITLE
cob docker test - support loading additional compose files

### ISSUE THREAD

**Issue by sivanbecker** [getweber/cob#146]
Today, cob docker test generates a compose file containing only cob subsystems (worker, db, wsgi, ..)
In my project i would like to also add another container for testing so that i can run in a fully contained env, not letting my tests communicate with the outside world.

### my thoughts are:
**cmdline would look like**: `cob docker test <.. today's args> --overlay-compose-file <additional compose file>`
**under the hood**: the new container/s should be added to the default testing network docker creates (was not aware of that but it seems it happens automatically if using docker-compose with multiple compose files)

**Comment by sivanbecker** [comment]
@vmalloc what do you think about this?
another option is to let `cob docker test` find additional compose files under tests folder ,under specific folder called tests/overlay_compose_files/

**Comment by vmalloc** [comment]
I dislike auto-discovery of overlays. Should be explicit IMO, if that's what you're asking

**Comment by sivanbecker** [comment]
@vmalloc 

So i added support for loading additional compose files. for example in my env in run:

`cob docker test -o ldap-docker-compose.yml -d 'ldap' -d 'phpldapadmin'` 

cob will look for this compose file under a specific folder tests/overlay_compose_files.
The file will be validated (existence and syntax) and dependencies will be added as asked.
