### ISSUE TITLE
Postgres port is hardcoded

### ISSUE THREAD

**Issue by oren0e** [getweber/cob#167]
https://github.com/getweber/cob/blob/5b23eb9c7431cbc814de9a0c9bf9a76ce3bf74ba/cob/utils/network.py#L9

This is a problem when e.g. I want to use 2 postgres dockers for developing different applications and I happen to map the port to something other than `5432`. It should be configurable.

**Comment by oren0e** [comment]
@vmalloc is it possible to make a release with the new changes?

**Comment by vmalloc** [comment]
@oren0e Yes. Unfortunately this repo needs a little housekeeping to get rid of Travis and move to GH actions. Will try to get to it soon
