### ISSUE TITLE
cob trying to access SQLite even though configuration points to Postgres

### ISSUE THREAD

**Issue by sivanbecker** [getweber/cob#45]
This is what I do that leads to this issue:
1. export COB_DATABASE_URI=postgresql+psycopg2://127.0.0.1/<db name>
2. dropdb <db name>
3. createdb <db name>
4. rm -rf migrations 
5. cob migrate init
6. cob migrate revision -m "init db"
7. cob migrate up

-> at this stage I can see that my postgresql db was created and the relevant tables from my models file were also created, everything seems fine.

8. cob testserver
9. run API request with curl -> db.sqlite is created and I get an error saying I cant perform my request due to missing tables in DB...

**Comment by vmalloc** [comment]
Did not reproduce.
