### ISSUE TITLE
Add `cob docker deploy` command

### ISSUE THREAD

**Issue by vmalloc** [getweber/cob#51]
This command should:

1. pull the docker image off its location
2. generate the deployment yml from within the container
3. run docker-compose on the generated configuration

NOTE: it should assert the image name in the yml file

**Comment by ayalash** [comment]
I think that this command should upgrade the DB in case needed

**Comment by vmalloc** [comment]
Docker deployments always perform upgrades when started, so it will do this automatically

**Comment by ayalash** [comment]
Great :)
Thanks

**Comment by vmalloc** [comment]
Remaining tasks:

- [ ] Support ExecStartPre
- [ ] Support ExecStop
