### ISSUE TITLE
change flask app run in development while running cob testserver

### ISSUE THREAD

**Issue by sivanbecker** [getweber/cob#99]
when running testserver , flask looks for FLASK_ENV.
if not defined, flask assumes production and prints a message on screen..

This variable can have the value 'development' and flask will know that this is a dev env.

so when running cob testserver FLASK_ENV should have the value 'development'

[flask docs about environment settings ](http://flask.pocoo.org/docs/1.0/cli/#environments)

**Comment by vmalloc** [comment]
After thinking about it for a while, and since the docs do not recommend setting FLASK_ENV from code, I think it would be best to just run `cob testserver` with the FLASK_ENV set manually. This also applies for celery workers run in testing mode...
